version: '3.8'

services:
  # 1. Database
  postgres-db:
    image: postgres:16-alpine
    container_name: express-ts-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Express API Backend
  api-server:
    build:
      context: ./server
      target: builder
    container_name: express-ts-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/mydb?schema=public
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres-db

  # 3. React Frontend Client
  client-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-vite-client
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api-server

volumes:
  postgres_data:
